[package]
name = "yag-template-analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
yag-template-syntax = { path = "../yag-template-syntax" }
slotmap = "1.0.7"
ecow = "0.2.2"
thiserror = "1.0"
rustc-hash = "2.0"
itertools = "0.13.0"
