[package]
name = "yag-template-analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8.11"
slotmap = "1.0.7"
yag-template-syntax = { path = "../yag-template-syntax" }
smol_str = "0.2.2"
