# Modelled on the corresponding typst-lsp workflow in
# https://github.com/nvarner/typst-lsp/blob/master/.github/workflows/release.yml.
#
# typst-lsp is released under the MIT license, copyright Nathan Varner.

name: Release on tag

on:
  push:
    tags:
      - 'v[0-9]*'

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/full-build.yml

  release:
    runs-on: ubuntu-latest
    needs: build
    if: success()
    permissions:
      # needed to create releases
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -R artifacts

      - uses: ncipollo/release-action@v1
        with:
          artifacts: 'artifacts/*/*'
          replacesArtifacts: true
          artifactErrorsFailBuild: true
          allowUpdates: true
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          body: ${{ format('Release {0}', github.ref_name) }}
          generateReleaseNotes: true
          makeLatest: true
