# Modelled on the corresponding typst-lsp workflow in
# https://github.com/nvarner/typst-lsp/blob/master/.github/workflows/release.yml.
#
# typst-lsp is released under the MIT license, copyright Nathan Varner.

name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    uses: ./.github/workflows/full-build.yml

  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: success() && startsWith(github.ref, 'refs/tags/')
    permissions:
      # needed to create releases
      contents: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -R artifacts

      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: 'artifacts/*/*'
          allowUpdates: true
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true

  publish-vscode:
    runs-on: ubuntu-latest
    needs: [build]
    if: success() && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v3

      - name: Deploy to VSCode Marketplace
        env:
          VSCE_PAT: ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
        run: npx vsce publish --packagePath $(find . -type f -iname '*.vsix')

      - name: Deploy to OpenVSX
        env:
          OVSX_PAT: ${{ secrets.OPENVSX_ACCESS_TOKEN }}
        run: npx ovsx publish --packagePath $(find . -type f -iname '*.vsix')
